name: CICD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven Project
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t 210447604094.dkr.ecr.ap-south-1.amazonaws.com/login-service:${{ github.run_number }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Authenticate With ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image
        run: |
          docker push 210447604094.dkr.ecr.ap-south-1.amazonaws.com/login-service:${{ github.run_number }} 